<a href="https://colab.research.google.com/github/raverielle/cloud_repo/blob/master/Numpy_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('hi')

hi


In [ ]:
import numpy as np
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
b=np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
q=[5,5,5,5,5,5,5,5,5,5]
c=np.array(q)
print(c)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
d=np.arange(10,50)
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
e=np.arange(10,50,2)
print(e)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
mlist=[[0,1,2],
       [3,4,5],
       [6,7,8]]
f=np.array(mlist)
print(f)
print(type(f))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
<class 'numpy.ndarray'>


In [ ]:
g=np.ones((3,3))
print(g)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
h=np.random.rand()
print(h)

0.3513361007109551


In [ ]:
i=np.random.randn(25)
print(i)

[ 0.73582538  0.77543527 -0.65981393 -0.75036648  0.17392647 -0.36248672
 -0.27914031  0.26614025  1.49520413  0.28839606 -2.04970386 -2.0907571
 -0.21273966 -0.13744021 -0.48021787  0.90555388 -0.83419278 -0.99452029
  0.59785424  0.54137733  0.07395713 -0.09699821  0.04349389 -0.66859142
 -0.33048484]


In [ ]:
y=np.linspace(0.01,1,100)
k=y.reshape(10,10)

print(k)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(mat[1:5, 1:5])

[[ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
print(mat[3,4])

20


In [ ]:
print(mat[0:3,1:2])

[[ 2]
 [ 7]
 [12]]


In [ ]:
print(mat[4:6])

[[21 22 23 24 25]]


In [ ]:
print(mat[3:6])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
p=np.sum(mat)
print(p)

325


In [ ]:
print(mat.std())

7.211102550927978


In [ ]:
print(sum(mat))

[55 60 65 70 75]
